import React from "react";
import Head from "next/head";
import Header from "../../../components/Header/Header";
import styles from "./index.module.css";
import { getSession } from "next-auth/react";
import { getMatch } from "../../../data/matches/MatchesMockApi";
import MatchCard from "../../../components/MatchCard/MatchCard";
import StadiumComponent from "../../../components/StadiumComponent/StadiumComponent";
const MatchComponent = ({ match, showControl }: any) => {
	return (
		<>
			<Head>
				<title>FIFA 2022</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			<div>
				<MatchCard
					asLink={false}
					match={match.match}
					showControl={showControl}
				/>
				<StadiumComponent
					stadium={{
						NumSeatsPerRow: match.match.NumSeatsPerRow,
						Number_Rows: match.match.Number_Rows,
						Name: match.match.Stadium,
						userSeats: match.match.UserList,
						reservedSeats: match.match.OtherList,
					}}
				/>
			</div>
		</>
	);
};

export default MatchComponent;

export async function getServerSideProps(context: any) {
	const session = await getSession(context);
	const headers = { Authorization: `Bearer ${session?.user?.token}` };
	const match = await getMatch({ ID: context.query.id }, headers);
	if (!match) {
		return { redirect: { permanent: false, destination: "/matches" } };
	}
	const time = new Date(match.match.Time);
	match.match.matchTime = time.toLocaleTimeString("sv-SE");
	match.match.matchDate = time.toLocaleDateString("sv-SE");
	return { props: { match, showControl: false } };
}
