import Head from "next/head";
import Header from "../components/header";
import Image from "next/image";
import Link from "next/link";
import { getSession } from "next-auth/react";
import type { GetServerSidePropsContext } from "next";

export default function Home() {
	return (
		<>
			<Head>
				<title>FIFA 2022</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="bg-red-700 w-screen h-screen">
				<Header />
				<div className="container flex flex-row justify-center py-8 flex-wrap gap-4">
					<div className="flex flex-col items-center flex-auto space-y-8">
						<Image
							className="w-auto "
							src="/logocup.png"
							width="100"
							height="100"
							alt="world cup"
						/>
						<Image
							className="w-auto filter-opacity-50 "
							src="/logoword.png"
							width="300"
							height="100"
							alt="world cup"
						/>
					</div>
					<div className="flex flex-col justify-center text-white font-bold text-xl">
						<h1 className="text-7xl text-orange-500">الحلم تحقق</h1>
						<h1 className="text-7xl mb-8 text-orange-500">المونديال عربي</h1>
						<p>تعال الآن و استكشف المزيد..</p>
						<Link
							href="/"
							className="rounded-full border-white border-2 max-w-fit py-1 px-3 block"
						>
							احجز تذكرتك الآن!
						</Link>
					</div>
				</div>
			</main>
		</>
	);
}
export async function getServerSideProps(context: GetServerSidePropsContext) {
	return { props: { session: await getSession(context) } };
}
