import React from "react";
import Header from "../../components/Header/Header";
import { getAllMatches } from "../../data/matches/MatchesMockApi";
import Head from "next/head";
import MatchCard from "../../components/MatchCard/MatchCard";
import { getSession } from "next-auth/react";
import { Role } from "../../types";
import Link from "next/link";
import styles from "./index.module.css";

type Props = {
	matches: Array<any>;
	showControl: Boolean;
};

export default function Matches({ matches, showControl }: Props) {
	
	return (
		<>
			<Head>
				<title>FIFA 2022</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<h1 className="text-center  text-3xl font-bold">Matches </h1>
			{showControl && (
				<Link href="/matches/new" className="block p-2 border-2 w-fit ml-auto">
					Create New
				</Link>
			)}
			<div className="bg-red-400 px-1 w-screen flex flex-wrap gap-2">
				{matches.map((match) => (
					<MatchCard
						key={match.ID}
						match={match}
						showControl={showControl}
						className={styles["match-card"]}
						asLink={true}
					/>
				))}
			</div>
		</>
	);
}

export async function getServerSideProps(context: any) {
	const session = await getSession(context);
	// Fetch data from external API
	const data = await getAllMatches({
		Authorization: `Bearer ${session?.user?.token}`,
	});
	data.matches.forEach((match: any) => {
		const time = new Date(match.Time);
		match.matchTime = time.toLocaleTimeString("sv-SE");
		match.matchDate = time.toLocaleDateString("sv-SE");
	});
	const showControl =
		session?.user?.role === Role.Manager || session?.user?.role === Role.Admin;
	return {
		props: { ...data, showControl }, // will be passed to the page component as props
	};
}
