import Match from "../../features/match/domain/Match";
import Header from "../../components/Header/Header";
import { getAllMatches } from "../../data/matches/MatchesMockApi";
import Head from "next/head";
import MatchCard from "../../components/MatchCard/MatchCard";
type Props = {
	matches: Match[];
};

export default function Matches({ matches }: Props) {
	return (
		<>
			<Head>
				<title>FIFA 2022</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			<div className="bg-red-400 px-1 w-screen h-full grid gap-2 sm:grid-cols-2 md:grid-cols-3 lg:auto-cols-fr">
				{matches.map((match) => (
					<MatchCard key={match.ID} match={match} />
				))}
			</div>
		</>
	);
}

export async function getStaticProps() {
	// Fetch data from external API
	const data = await getAllMatches();
	data.matches.forEach((match: any) => {
		const time = new Date(match.Time);
		match.matchTime = time.toLocaleTimeString("en-US");
		match.matchDate = time.toLocaleDateString();
	});
	return {
		props: { ...data }, // will be passed to the page component as props
	};
}
