import React from "react";
import Head from "next/head";
import Header from "../../components/header";
import UserCard from "../../components/UserCard/UserCard";
import { getSession } from "next-auth/react";
import { Role } from "../../types";

const index = ({ Users, currentUserRole }: any) => {
	return (
		<>
			<Head>
				<title>FIFA 2022</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<h1 className="text-center tracking-wider text-xl">Users</h1>

			<div className="py-2 space-y-2 bg-slate-200">
				{Users.map((user: any) => (
					<UserCard
						key={`user-${user.ID}`}
						user={user}
						showControls={currentUserRole === "0"}
					/>
				))}
			</div>
		</>
	);
};

export default index;

export async function getServerSideProps(context: any) {
	// Fetch data from external API
	const session = await getSession(context);
	if (!session) {
		return {
			redirect: {
				permanent: false,
				destination: "/signin",
			},
		};
	} else if (session?.user?.Role !== Role.admin) {
		return {
			redirect: {
				permanent: false,
				destination: "/NotAuthorized",
			},
		};
	}

	const response = await fetch(`http://localhost:8080/users`);
	const usersData = await response.json();
	return {
		props: { ...usersData, currentUserRole: session?.user?.Role }, // will be passed to the page component as props
	};
}
